### PR TITLE
adding stemplot to readme

### PR DESCRIPTION
**Pull request by nanobowers**
Per @kojix2  request in issue #56 

I am unsure how to generate png images in the same style as the original documentation, so instead just added some markdown.  That said, the stemplot is not as graphical as the other plot types.

### CODE REVIEW

**Comment by kojix2** [comment]
Yes, I think it's better to keep the same image style if possible. 
But I do appreciate your effort on this pull request!

**Comment by nanobowers** [comment]
@kojix2 Maybe if @mrkn can provide the terminal settings and font selection, then i can produce .png images similar to the other one images he has given using the examples?  Or perhaps this is a better request for @mrkn ?  Feel free to use whichever examples (either in this PR or in the examples/ex_stemplot.rb)...

**Comment by mrkn** [comment]
I will do it. But, maybe I cannot do it soon because I'm very busy this month.

**Comment by nanobowers** [comment]
Withdrawing this pull request, since @mrkn has offered to do this in a consistent style with the other images.

**Pull request closed without merging**
